# Generated by Django 2.2.4 on 2019-08-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('capasity', models.IntegerField()),
                ('free_slots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_image', models.ImageField(blank=True, upload_to='images/')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_park', to='park.Park')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parks', to='park.Park')),
            ],
        ),
        migrations.CreateModel(
            name='Feasibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.IntegerField()),
                ('park_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='park.ParkSlot')),
            ],
        ),
    ]
